apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "visit.fullname" . }}
spec:
  tls:
    - hosts:
      - helm.visit.shrugcoding.click
      secretName: visit-secret
  rules:
    - host: helm.visit.shrugcoding.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "visit.fullname" . }}
                port:
                  number: 80