apiVersion: v1
kind: Service
metadata:
 name: service-visit
spec:
 type: LoadBalancer
 selector:
    app: pod-visit
 ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "80"
    port: 80
    targetPort: 80
