apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visit.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ include "visit.fullname" . }} 
  template:
    metadata: 
      labels:
        app: {{ include "visit.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ include "visit.fullname" . }}
        ports:
        - name: http
          containerPort: 4200