config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "backend.minikube.local/guestbook"
image:
  repository: rsming/visit
  tag: "1.0"
replicaCount: 3
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  host: visit.127.0.0.1.xip.io